spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 1945374160@qq.com
    password: wtyltrukhavjfbcg
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    addresses: 3.106.124.14
  security:
    filter:
        order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver